In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Embedding, Dense

In [2]:
text = """
You are capable of more than you think. Every small step you take is proof of your strength.
You are learning, you are growing, and that is enough. You deserve good things, even on the days you doubt yourself.
Your effort matters, even when nobody notices. Progress may feel slow, but it is still progress.

It’s okay to feel confused; clarity comes after consistency. You don’t need to be perfect; you only need to try.
Your feelings are real, and they deserve respect. You are not falling behind; you are moving at your own pace.
You’ve overcome challenges before — you will overcome this too.

Every challenge is a chance to grow stronger. Mistakes are lessons in disguise; don’t fear them.
Curiosity is your greatest strength — keep asking questions. Improvement is a journey of patience and kindness to yourself.
Skills take time to build; confidence takes practice.

Sometimes you don’t know where you’re going, but you still need to move.
Some days are heavy, but you still choose to show up — that’s bravery.
It’s normal to want reassurance; it means you care.
You don’t have to be motivated every day; discipline will carry you.
You’re learning to trust yourself again, and that’s beautiful.

I am worthy of respect. I can learn anything with enough time.
I choose progress over perfection. I am strong, even when I feel weak.
I trust myself more every day.

There was a time when you doubted your abilities, but you still took the first step.
That moment changed everything. You once thought you couldn’t handle pressure,
but you adapted, survived, and grew. You proved to yourself that hard work beats talent
when talent doesn’t work hard. You’ve had failures, but every time, you stood up stronger.
Your journey is messy, painful, beautiful, and uniquely yours — and it’s shaping you.

Imagine waking up one day feeling proud because you didn’t quit.
Imagine someone telling you that your journey inspired them.
Imagine looking back and realizing this difficult phase was the turning point.
Imagine becoming the version of yourself you’re afraid to believe in.
"""


In [3]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])

word_index = tokenizer.word_index
total_words = len(word_index) + 1

print("Total words:", total_words)


Total words: 192


In [4]:
input_sequences = []

for line in text.split("\n"):
    tokens = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(tokens)):
        seq = tokens[:i+1]
        input_sequences.append(seq)

print("Total sequences:", len(input_sequences))


Total sequences: 324


In [5]:
#Pad Sequences. Make all sequences equal length.
max_len = max([len(x) for x in input_sequences])
input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_len, padding='pre'))

X = input_sequences[:, :-1]
y = input_sequences[:, -1]


In [6]:
X

array([[  0,   0,   0, ...,   0,   0,   1],
       [  0,   0,   0, ...,   0,   1,   3],
       [  0,   0,   0, ...,   1,   3,  57],
       ...,
       [  0,   0,   0, ...,  11,  27, 190],
       [  0,   0,   0, ...,  27, 190,   2],
       [  0,   0,   0, ..., 190,   2, 191]], shape=(324, 20), dtype=int32)

In [7]:
y

array([  3,  57,   9,  30,  58,   1,  59,  10,  60,  31,   1,  32,   6,
        61,   9,   4,  33,   3,  34,   1,   3,  62,   5,  12,   6,  35,
         1,  36,  63,  64,  20,  65,  13,  37,   1,  66,  11,  67,  68,
        20,  14,  69,  70,  21,  71,  22,  72,   7,  38,   6,  15,  21,
        73,   2,  22,  74,  75,  76,  77,  78,   1,  16,  24,   2,  39,
        79,   1,  80,  24,   2,  81,  82,   3,  83,   5,  84,  36,  40,
         1,   3,  85,  86,  87,   1,   3,  88,  89,   4,  90,  91,  42,
        92,  93,  17,   1,  43,  42,  44,  94,  95,   6,  25,  96,   2,
        97,  45,  98,   3,  99,  46, 100,  16, 101,  47,   6,   4, 103,
        33,  17, 104, 105, 106, 107,   6,  25,  26,   9, 108,   5, 109,
         2,  11,  32,  18,   2, 111, 112, 113, 114,   1,  16, 116, 117,
        27, 118,   7,   1,  15,  24,   2, 119,  37,   3, 121,   7,   1,
        15,  48,   2, 122,  28,  17,  49, 123, 124,   2, 125, 126,  38,
       127,   1, 128,  16, 129,   2,  39, 130,  10,  29, 131,  4

In [8]:
# build lstm model
model = Sequential()
model.add(Embedding(total_words, 64, input_length=max_len-1))
model.add(LSTM(64))
model.add(Dense(total_words, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()


C:\Anaconda3\envs\ts_env\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
y = tf.keras.utils.to_categorical(y, num_classes=total_words)


In [10]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(324, 192))

In [11]:
history = model.fit(X, y, epochs=200, verbose=1)

Epoch 1/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.0463 - loss: 5.2555
Epoch 2/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0772 - loss: 5.2281
Epoch 3/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.0772 - loss: 5.1295
Epoch 4/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0772 - loss: 4.9906
Epoch 5/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.0772 - loss: 4.9282
Epoch 6/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0772 - loss: 4.8906
Epoch 7/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0772 - loss: 4.8727
Epoch 8/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0772 - loss: 4.8517
Epoch 9/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.0772 - loss: 4.8363
Epoch 10/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0772 - loss: 4.8075
Epoch 11/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.0772 - loss: 4.7827
Epoch 12/200
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accur

In [12]:
history

In [13]:
#predict next words
def predict_next_word(seed_text):
    token_list = tokenizer.texts_to_sequences([seed_text])[0]
    token_list = pad_sequences([token_list], maxlen=max_len-1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_index = np.argmax(predicted)
    
    for word, index in word_index.items():
        if index == predicted_index:
            return word

In [20]:
print(predict_next_word("clarity comes after"))

time


In [21]:
print(predict_next_word("Your feelings are"))

real


In [22]:
print(predict_next_word("Some days are heavy, but you still"))

choose
